### ISSUE TITLE
when i download ts file use https, it has error : "not support the protocol https"

### ISSUE THREAD

**Issue by siyrs** [yadavkohi/FFmpegSO#2]
when i download ts file use https, it has error : "not support the protocol https" .

**Comment by siyrs** [comment]
cmd is "ffmpeg -i https://xxx.xxx.com/index.m3u8 out.mp4"

**Comment by yadavkohi** [comment]
I have created the ffmpeg .so file for audio and video operations. So not sure whether it will download file or not.

**Comment by siyrs** [comment]
Thanks. I have change the "https" to "http" . And it is work .
